[package]
name = "orchestrator_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.13"
ic-stable-structures = "0.6.8"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
bincode = "1.3"
ic-cdk-timers = "0.7"
evm_logs_types = { path = "../evm_logs_types" }
hex = "0.4"
ic-metrics-encoder = "1"


[build-dependencies]
ic-cdk-bindgen = "0.1"
