[package]
name = "evm_logs_types"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { version = "0.10" }
ic-cdk = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
