edition = "2021"
version = "Two"
max_width = 120
tab_spaces = 4
newline_style = "Unix"
fn_params_layout = "Tall"
match_arm_leading_pipes = "Preserve"
format_code_in_doc_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true