[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
pocket-ic = "6.0.0"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
evm_logs_types = { path = "../evm_logs_types" }
evm_rpc_types.workspace = true
chain_service_canister = { path = "../chain_service_canister" }
orchestrator_canister = { path = "../orchestrator_canister" }

[[test]]
name = "orchestrator_integration_tests"
path = "tests/orchestrator_integration_tests.rs"

[[test]]
name = "chain_service_integration_tests"
path = "tests/chain_service_integration_tests.rs"

[[test]]
name = "end_to_end_workflow_tests"
path = "tests/end_to_end_workflow_tests.rs"
